version: '3.8'

services:
  web:
    build:
      context: .
    ports:
    - 8080:5000
    environment:
    - FLASK_ENV=development
    volumes: 
    - ./:/app

  mysqldb:
    image: mysql
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    volumes:
    - mysql:/var/lib/mysql
    - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: